---
title: "Geriatric Institutional Assessment Profile (GIAP) Summary Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, comment=NA, fig.width = 6, fig.asp = 0.9, out.width = "90%", fig.align = "center", dev='svg')
```

```{r}
library(openxlsx)
library(tidyverse)
library(ggthemes)
library(scales)
library(data.table)
library(haven)
library(pander)
library(lme4)
library(emmeans)
library(pander)

panderOptions('table.split.table', Inf)

NICHE_colors <- c("#57068C","#6199AE","#FFC842","#314383","#6BAB8A","#F09C5D")
```

```{r}
giap <- read_sav("Feb 2019 Data.sav")

wrap_20 <- wrap_format(20)
wrap_30 <- wrap_format(30)
wrap_40 <- wrap_format(40)

giap <- giap %>% 
  rename("Hospital.Name" = "facilityName") %>% 
  rename("Unit" = "primaryNursingUnit") %>%
  rename("Hospital.ID" = "facilityID" ) %>% 
  mutate(Hospital.Name = as.factor(Hospital.Name),
         Unit = as.factor(Unit),
         Hospital.ID = as.factor(Hospital.ID),
         ID = c(1:nrow(.)))
```

# Coefficient Alpha for Scales
## Resource Availability
```{r}
myalpha <- giap %>%
  filter(!is.na(Hospital.ID)) %>%
  select(Hospital.ID, ID, Q8_1, Q8_2, Q8_3, Q8_5, Q8_6, Q8_7, Q8_10, Q8_11, Q8_12) %>%
  gather(Item, Response, -Hospital.ID, -ID) %>% 
  filter(!is.na(Response)) %>%
  select(Hospital.ID, ID, Item, Response) %>%
  mutate(Item = as.factor(Item)) %>% 
  spread(key=Item, value=Response) %>%
  select(-Hospital.ID, -ID) %>%
  psych::alpha(check.keys=TRUE)

myalpha[1:4] %>% pander()

```

## Age-Sensitive Care
```{r}
myalpha <- giap %>%
  filter(!is.na(Hospital.ID)) %>%
  select(Hospital.ID, ID, Q7_1, Q7_2, Q7_3, Q7_4, Q7_5, Q7_7, Q7_8, Q7_9, Q7_10, Q7_11, Q7_12, Q7_13) %>%
  gather(Item, Response, -Hospital.ID, -ID) %>% 
  filter(!is.na(Response)) %>%
  select(Hospital.ID, ID, Item, Response) %>%
  mutate(Item = as.factor(Item)) %>% 
  spread(key=Item, value=Response) %>%
  select(-Hospital.ID, -ID) %>%
  psych::alpha(check.keys=TRUE)


myalpha[1:4] %>%pander()
```

## Implementation Climate
```{r}
myalpha <- giap %>%
  filter(!is.na(Hospital.ID)) %>%
  select(Hospital.ID, ID, Q7_26, Q7_27, Q7_28, Q7_29, Q7_30) %>%
  gather(Item, Response, -Hospital.ID, -ID) %>% 
  filter(!is.na(Response)) %>%
  select(Hospital.ID, ID, Item, Response) %>%
  mutate(Item = as.factor(Item)) %>% 
  spread(key=Item, value=Response) %>%
  select(-Hospital.ID, -ID) %>%
  psych::alpha(check.keys=TRUE)

myalpha[1:4] %>%pander()


```

## Organization Values
```{r}
myalpha <- giap %>%
  filter(!is.na(Hospital.ID)) %>%
  select(Hospital.ID, ID, Q7_19, Q7_20, Q7_21, Q7_23, Q7_24) %>%
  gather(Item, Response, -Hospital.ID, -ID) %>% 
  filter(!is.na(Response)) %>%
  select(Hospital.ID, ID, Item, Response) %>%
  mutate(Item = as.factor(Item)) %>% 
  spread(key=Item, value=Response) %>%
  select(-Hospital.ID, -ID) %>%
  psych::alpha(check.keys=TRUE)

myalpha[1:4] %>%pander()
```

# Factor Analysis
## Resource Availability
```{r}
giap %>%
  filter(!is.na(Hospital.ID)) %>%
  select(Hospital.ID, ID, Q8_1, Q8_2, Q8_3, Q8_5, Q8_6, Q8_7, Q8_10, Q8_11, Q8_12) %>%
  gather(Item, Response, -Hospital.ID, -ID) %>% 
  filter(!is.na(Response)) %>%
  select(Hospital.ID, ID, Item, Response) %>%
  spread(Item, Response) %>%
  select(-Hospital.ID, -ID) %>%
  na.omit() %>%
  factanal(factors = 1)
```

## Age-Sensitive Care
```{r}
giap %>%
  filter(!is.na(Hospital.ID)) %>%
  select(Hospital.ID, ID, Q7_1, Q7_2, Q7_3, Q7_4, Q7_5, Q7_7,
         Q7_8, Q7_9, Q7_10, Q7_11, Q7_12, Q7_13) %>%
  gather(Item, Response, -Hospital.ID, -ID) %>% 
  filter(!is.na(Response)) %>%
  select(Hospital.ID, ID, Item, Response) %>%
  spread(Item, Response) %>%
  select(-Hospital.ID, -ID) %>%
  na.omit() %>%
  factanal(factors = 1)
```

## Implementation Climate
```{r}
giap %>%
  filter(!is.na(Hospital.ID)) %>%
  select(Hospital.ID, ID, Q7_26, Q7_27, Q7_28, Q7_29, Q7_30) %>%
  gather(Item, Response, -Hospital.ID, -ID) %>% 
  filter(!is.na(Response)) %>%
  select(Hospital.ID, ID, Item, Response) %>%
  spread(Item, Response) %>%
  select(-Hospital.ID, -ID) %>%
  na.omit() %>%
  factanal(factors = 1)
```

## Organizational Values
```{r}
giap %>%
  filter(!is.na(Hospital.ID)) %>%
  select(Hospital.ID, ID, Q7_19, Q7_20, Q7_21, Q7_23, Q7_24) %>%
  gather(Item, Response, -Hospital.ID, -ID) %>% 
  filter(!is.na(Response)) %>%
  select(Hospital.ID, ID, Item, Response) %>%
  spread(Item, Response) %>%
  select(-Hospital.ID, -ID) %>%
  na.omit() %>%
  factanal(factors = 1)
```

## Knowledge

```{r}
Falls <- c("Q42b", "Q43c")
Skin <- c("Q44c", "Q45b")
Assess <- c("Q46b", "Q51b")
Delirium <- c("Q47a")
Urinary <- c("Q48d", "Q49c")
Nutrition <- c("Q50b", "Q58c", "Q59b")
Sleep <- c("Q52a", "Q56b")
Dementia <- c("Q53b", "Q55c")
Medication <- c("Q54c", "Q57b")
Depression <- c("Q60c", "Q61b")

na_to_zero <- function(val){
  zero <- ifelse(is.na(val), 0, val)
  return(zero)
}
```

```{r}
pacman::p_load(ltm)

score <- giap %>%
  dplyr::select(Hospital.ID, ID, Q42b, Q43c, Q44c, Q45b, Q46b, Q51b, Q47a, Q48d, Q49c, Q50b, Q58c, Q59b, Q52a,
                Q56b, Q53b, Q55c, Q54c, Q57b, Q60c, Q61b) %>% 
  mutate_at(vars("Q42b", "Q43c", "Q44c", "Q45b", "Q46b", "Q51b", "Q47a", "Q48d", "Q49c",
         "Q50b", "Q58c", "Q59b", "Q52a", "Q56b", "Q53b", "Q55c", "Q54c", "Q57b", "Q60c", "Q61b"), na_to_zero) %>%
  mutate(Falls = 0,
         Falls = ifelse(as.numeric(Q42b) == 1, Falls + 1, Falls + 0),
         Falls = ifelse(as.numeric(Q43c) == 1, Falls + 1, Falls + 0),
         Skin = 0,
         Skin = ifelse(as.numeric(Q44c) == 1, Skin + 1, Skin + 0),
         Skin = ifelse(as.numeric(Q45b) == 1, Skin + 1, Skin + 0),
         Assess = 0,
         Assess = ifelse(as.numeric(Q46b) == 1, Assess + 1, Assess + 0),
         Assess = ifelse(as.numeric(Q51b) == 1, Assess + 1, Assess + 0),
         Delirium = 0,
         Delirium = ifelse(as.numeric(Q47a) == 1, Delirium + 1, Delirium + 0),
         Urinary = 0,
         Urinary = ifelse(as.numeric(Q48d) == 1, Urinary + 1, Urinary + 0),
         Urinary = ifelse(as.numeric(Q49c) == 1, Urinary + 1, Urinary + 0),
         Nutrition = 0,
         Nutrition = ifelse(as.numeric(Q59b) == 1, Nutrition + 1, Nutrition + 0),
         Nutrition = ifelse(as.numeric(Q50b) == 1, Nutrition + 1, Nutrition + 0),
         Nutrition = ifelse(as.numeric(Q58c) == 1, Nutrition + 1, Nutrition + 0),
         Sleep = 0,
         Sleep = ifelse(as.numeric(Q52a) == 1, Sleep + 1, Sleep + 0),
         Sleep = ifelse(as.numeric(Q56b) == 1, Sleep + 1, Sleep + 0),
         Dementia = 0,
         Dementia = ifelse(as.numeric(Q53b) == 1, Dementia + 1, Dementia + 0),
         Dementia = ifelse(as.numeric(Q55c) == 1, Dementia + 1, Dementia + 0),
         Medication = 0,
         Medication = ifelse(as.numeric(Q54c) == 1, Medication + 1, Medication + 0),
         Medication = ifelse(as.numeric(Q57b) == 1, Medication + 1, Medication + 0),
         Depression = 0,
         Depression = ifelse(as.numeric(Q60c) == 1, Depression + 1, Depression + 0),
         Depression = ifelse(as.numeric(Q61b) == 1, Depression + 1, Depression + 0),
         Total = Falls + Skin + Assess + Delirium + Urinary + Nutrition + Sleep + Dementia + Medication +
           Depression)
```

```{r}
questions <- colnames(score)[23:32]
score_m <- score %>% as.matrix()
```

```{r}
point_biserial_question <- function(Questions, Answers, Metric){
  metric_score <- c()
  question_list <- c()
  for(question in Questions){
    metric_score <- c(metric_score, biserial.cor(as.numeric(score_m[,Metric]),
                                                 as.numeric(score_m[,question]), 
                                                 level = 2))
    question_list <- c(question_list, question)
  }
  return(list("Score" = metric_score, 
              "Questions" = rep(Metric, length(metric_score))))
}
```

### Point Bi-Serial Analysis

```{r}
cat_list <- c()
question_list <- c()
metric_score <- c()
total_metric_score <- c()
for(question in questions){
  Q <- get(question)
  question_list <- c(question_list, Q)
  cat_values <- point_biserial_question(Q, score_m, question)
  cat_metric_score <- c(metric_score, cat_values$Score)
  total_values <- point_biserial_question(Q, score_m, "Total")
  total_metric_score <- c(total_metric_score, total_values$Score)
  cat_list <- c(cat_list, cat_values$Questions)
}

data.frame("Category" = cat_list, "Question" = question_list, "Point Bi-Serial Category" = cat_metric_score, "Point Bi-Serial Total" = total_metric_score) %>% pander()
```







